- name: exam-iac
  gather_facts: false
  hosts: [all]
  become: yes

  tasks:
    - name: Create exam-iac-app2
      docker_container:
        name: wordpress
        image: wordpress
        pull: true
        state: started
        recreate: yes
        restart: yes
        ports:
          - "80:80"
        env:
          WORDPRESS_DB_HOST: $db
#terraform-20210223082716228000000001.c3texek9fy5h.eu-central-1.rds.amazonaws.com
          WORDPRESS_DB_USER: iteauser
          WORDPRESS_DB_PASSWORD: q1q1q1q1
          WORDPRESS_DB_NAME: iteadb

