- name: exam-iac
  gather_facts: false
  hosts: [all]
  become: yes
  vars_files:
    - db-address.yml

  tasks:
    - name: Create exam-iac-app2
      docker_container:
        name: wordpress
        image: wordpress
        pull: true
        state: started
        recreate: yes
        restart: yes
        ports:
          - "80:80"
        env:
          WORDPRESS_DB_HOST: "{{ db }}"
          WORDPRESS_DB_USER: iteauser
          WORDPRESS_DB_PASSWORD: q1q1q1q1
          WORDPRESS_DB_NAME: iteadb

